# Generated by Django 2.2 on 2020-11-14 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201114_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageconnector',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exits', to='pages.Page'),
        ),
        migrations.AlterField(
            model_name='pageconnector',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrypoints', to='pages.Page'),
        ),
    ]
