# Generated by Django 2.2 on 2020-11-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201114_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='right',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
