# Generated by Django 2.2 on 2020-11-15 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201114_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='right',
            new_name='top',
        ),
    ]
