# Generated by Django 2.2 on 2020-11-16 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20201115_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageconnector',
            name='origin',
        ),
    ]
